# Generated by Django 3.1.2 on 2021-04-20 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AllergoBuster5000', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagebuch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_stamp', models.DateTimeField(auto_now_add=True)),
                ('date_stamp', models.DateField(auto_now_add=True)),
                ('Abies', models.FloatField(default=0, max_length=20)),
                ('Acer', models.FloatField(default=0, max_length=20)),
                ('Aesculus', models.FloatField(default=0, max_length=20)),
                ('Alnus', models.FloatField(default=0, max_length=20)),
                ('Ambrosia', models.FloatField(default=0, max_length=20)),
                ('Artemisia', models.FloatField(default=0, max_length=20)),
                ('Asteraceae', models.FloatField(default=0, max_length=20)),
                ('Betula', models.FloatField(default=0, max_length=20)),
                ('Carpinus', models.FloatField(default=0, max_length=20)),
                ('Castanea', models.FloatField(default=0, max_length=20)),
                ('Chenopodium', models.FloatField(default=0, max_length=20)),
                ('Corylus', models.FloatField(default=0, max_length=20)),
                ('Cruciferae', models.FloatField(default=0, max_length=20)),
                ('Cyperaceae', models.FloatField(default=0, max_length=20)),
                ('Erica', models.FloatField(default=0, max_length=20)),
                ('Fagus', models.FloatField(default=0, max_length=20)),
                ('Fraxinus', models.FloatField(default=0, max_length=20)),
                ('Fungus', models.FloatField(default=0, max_length=20)),
                ('Galium', models.FloatField(default=0, max_length=20)),
                ('Humulus', models.FloatField(default=0, max_length=20)),
                ('Impatiens', models.FloatField(default=0, max_length=20)),
                ('Juglans', models.FloatField(default=0, max_length=20)),
                ('Larix', models.FloatField(default=0, max_length=20)),
                ('Picea', models.FloatField(default=0, max_length=20)),
                ('Pinaceae', models.FloatField(default=0, max_length=20)),
                ('Pinus', models.FloatField(default=0, max_length=20)),
                ('Plantago', models.FloatField(default=0, max_length=20)),
                ('Platanus', models.FloatField(default=0, max_length=20)),
                ('Poaceae', models.FloatField(default=0, max_length=20)),
                ('Populus', models.FloatField(default=0, max_length=20)),
                ('Quercus', models.FloatField(default=0, max_length=20)),
                ('Quercus_ilex', models.FloatField(default=0, max_length=20)),
                ('Rumex', models.FloatField(default=0, max_length=20)),
                ('Salix', models.FloatField(default=0, max_length=20)),
                ('Sambucus', models.FloatField(default=0, max_length=20)),
                ('Secale', models.FloatField(default=0, max_length=20)),
                ('Taxus', models.FloatField(default=0, max_length=20)),
                ('Tilia', models.FloatField(default=0, max_length=20)),
                ('Ulmus', models.FloatField(default=0, max_length=20)),
                ('Urtica', models.FloatField(default=0, max_length=20)),
                ('Varia', models.FloatField(default=0, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollenDaten', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
