# Generated by Django 3.1.2 on 2021-04-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllergoBuster5000', '0002_tagebuch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Listen',
            field=models.ManyToManyField(blank=True, related_name='rel_Listen', to='AllergoBuster5000.Tagebuch'),
        ),
    ]
