# Generated by Django 3.1.2 on 2021-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllergoBuster5000', '0003_user_listen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Listen',
        ),
        migrations.AddField(
            model_name='tagebuch',
            name='feeling',
            field=models.CharField(choices=[('SS', 'Sehr Schlecht'), ('SC', 'Schlecht'), ('NM', 'Normal'), ('GT', 'Gut'), ('SG', 'Sehr Gut')], default='Normal', max_length=2),
        ),
    ]
